leftnav:
- identifier: f203c177-3fa5-4903-ef15-c0736104ff45
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: b975a029-eae6-ea5c-ebd4-396537ee6200
  name: Calendar
  pageRef: /pages/calendar
  weight: 20
- identifier: b0daf727-e23a-7964-1128-c102a7960502
  name: Readings
  pageRef: /pages/readings
  weight: 30
- identifier: 050715ff-b86c-a406-0f24-ee95e87f03cc
  name: Assignments
  pageRef: /pages/assignments
  weight: 40
- identifier: 0cae823a-9118-fb46-254d-db91ac346990
  name: Study Materials
  pageRef: /pages/study-materials
  weight: 50
